#include "my_file.h"

// We don't need to include <iostream> here.
// It is part of the precompiled header cmake_pch.h which is
// generated by CMake and force-included to all source files
// of the target

void my_func() {
  std::cout << "Precompiled headers are cool!\n";
}